name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Project Checkout
        uses: actions/checkout@v2.4.0

      - name: Run unit tests
        uses: thundra-io/thundra-gradle-test-action@v1.0.4
        with:
          apikey: ${{ secrets.THUNDRA_API_KEY }}
          project_id: ${{ secrets.THUNDRA_PROJECT_ID }}
          command: ./gradlew clean test --rerun-tasks --stacktrace
